### ISSUE TITLE
bulk donations pattern mining

### ISSUE THREAD

**Issue by zwanalexz** [0x9simon/slaysybil#4]
When Gitcoin donates, it comes with the batch donation function. You really don't know about Gitcoin. It's funny. You can even win the championship.

**Comment by 0x9simon** [comment]
We know the function of batch donations in Gitcoin. In the Hackathon, we demo the approaches. It does NOT mean that the list will be used as 100% Sybil in Gitcoin and other projects.

**Comment by zwanalexz** [comment]
You will make many people misunderstand
