### ISSUE TITLE
You will kill this great donation platform--gitcoin

### ISSUE THREAD

**Issue by Voltwallet** [0x9simon/slaysybil#5]
1:The gitcoin platform hopes that customers in the encrypted world will select projects they think are good for sponsorship. You went so far as to filter out what you think are Sybil attackers among those who donate at G15. The consequence of your doing this is that in the next G16, only some people or no one may be willing to donate to gitcoin. Because they are afraid that you, the champion, will put the label of witch on them. You will kill the gitcoin platform.
2:Bulk donations are a prominent feature of gitcoin. Because gitcoin is a very user-friendly platform, they understand the needs of customers (customers know that not only one of these projects is good, and they want to support multiple projects at once). You regard this function as an important condition for screening witches, and you will kill the gitcoin platform

**Comment by 0x9simon** [comment]
Yes We defenitely know the function of bulk donations. And the hackathon only require us to demo the approaches that could be used in sybil prevention. It does NOT mean that the list will be deemed as 100% Sybils for Gitcoin and other projects.

**Comment by Voltwallet** [comment]
What would you do if a project used your address? Compensation for these addresses that you listed as high risk?
